name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1

        env:
          # CIBW_BEFORE_ALL_WINDOWS: pip install delvewheel && echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH && echo "C:\msys64\usr\bin" >> $GITHUB_PATH && gfortran --version
          CIBW_BEFORE_ALL_WINDOWS: vcpkg.exe install pthread && nuget.exe install pthread
          CIBW_BEFORE_ALL_LINUX: yum install -y libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel
          CIBW_BEFORE_BUILD: python3 .github/build_dependencies.py
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: export LD_LIBRARY_PATH=/project/lib && auditwheel repair -w {dest_dir} {wheel}
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: delvewheel repair -w {dest_dir} {wheel}

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
