name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_BUILD: bash .github/prepare_build.sh && bash .github/build_GLEW.sh && bash .github/build_CBLAS.sh

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
